# Generated by Django 3.2.7 on 2022-03-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(help_text='사용자 닉네임', max_length=200, unique=True),
        ),
    ]
