# Generated by Django 3.2.7 on 2022-02-23 12:13

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_party_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
    ]
