# Generated by Django 3.2.7 on 2022-02-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_party_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='location',
        ),
    ]
