# Generated by Django 3.2.7 on 2022-03-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_auto_20220306_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['-order_time']},
        ),
    ]
